### DISCUSSION TITLE
Flexibility in the use of tags using matrix

### DISCUSSION THREAD

**Discussion by bruno561** [arcxp/datadog-service-catalog-metadata-provider#30] [Q&A] [answered]
Currently I use this custom action in a reusable workflow. This reusable workflow is called by a caller workflow that has a matrix.

```
strategy:
      matrix:
        tags: [{ tag1: "value1", tag2: "value2" }]
```

 In reusable Workflow I use the following scheme:

```
tags: | 
  - "${{ inputs.tagName1 }}" 
  - "${{ inputs.tagName2 }}"
```
 
However, this way you are limited to just two tags, "tagName1" and "tagName2". I believe that because the tags are a list of dictionaries. Is there any workaround for this situation?

P.S.: Of all the metadata fields, it's the only one that I can't make flexible using the matrix, that is, include the number of tags I want in the matrix, without having to change the schema.

**Comment by manchicken** [comment]
Do you have a sample workflow I can look at, especially if you're using it for other fields? This is certainly something that looks interesting, I'd like to see what I can do to help you here.

**Comment by bruno561** [comment]
Yep! Basically I followed the README.md and I use a caller workflow with matrix for the variables in the reusable workflow.

```
    steps:
      ...
      - name: Service Definition
        uses: arcxp/datadog-service-catalog-metadata-provider@v1.x.x
        with:
          ...
          service-name: ${{ inputs.serviceName }}
          team: ${{ inputs.squadName }}
          email: ${{ inputs.emailName }}
          slack-support-channel: ${{ inputs.slackChannelName }}
          docs: |
            - name: Documentation
              url: ${{ inputs.docUrl }}
              provider: XPTO
          links: |
            - name: Grafana
              url: ${{ inputs.grafanaUrl }}
              type: url
          repos: |
            - name: ${{ github.event.repository.name }}
              url: ${{ github.server_url }}/${{ github.repository }}/services/${{ inputs.serviceName }}
              provider: GitHub
          tags: |
            - "${{ inputs.tagName1 }}"
            - "${{ inputs.tagName2 }}"
```

**Comment by bruno561** [comment]
Do you need Caller Workflow too? @manchicken

**Reply by manchicken** [reply]
Naw, but if you could give me a complete example with matrix, that would be helpful. Even if it doesn't work, I'm just trying to see how you envision this working.

If you could give me a complete example with any sensitive information redacted that would be super helpful.

**Reply by bruno561** [reply]
@manchicken 

```
name: caller_workflow
...
jobs:
  create-service-definition:
    strategy:
      matrix:
        service: [something]
        squad: [something]
        email: [something@something.com]
        slack-channel: ["something"]
        docs: ["something"]
        links: ["something"]
        tags: [{tag1: "key1:something", tag2: "key2:something"}]
      fail-fast: false
    uses: reusable_workflow@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      squadName: ${{ matrix.squad }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-channel }}
      docUrl: ${{ matrix.docs }}
      grafanaUrl: ${{ matrix.links }}
      tagName1: ${{ matrix.tags.tag1 }}
      tagName2: ${{ matrix.tags.tag2 }}
```
In this example, if I need a third tag, I need to edit my Reusable Workflow by putting:

```
          tags: |
            - "${{ inputs.tagName3 }}"
```
So, this makes it inflexible when working with the matrix. The idea of working with the matrix is that each service can have a number of different tags. Example service 1 has 2 tags. Service 2 has 3 tags. Services 3 has 5 tags.

The matrix works perfectly when we work with other attributes, such as services. That is, in the Reusable Workflow I only need to put this `service-name: ${{ inputs.serviceName }}` and I can put as many services as I want in the Caller Workflow.

**Reply by manchicken** [reply]
~Didn't you say there was a matrix? I'm sorry if I'm misremembering.~

Thanks, this should be good. I'll dig in.

**Reply by manchicken** [reply]
Oooh, I think I figured out the issue! I think it's that your shape is weird.

Remember that the inputs are actually _scalar strings_, not nested Objects, in how they're expressed in your workflow. I'll add this to documentation, and also add a test to show how this should be done. Give me a few and I'll have something.

**Reply by bruno561** [reply]
Nice! And is there a way to work with tags in a flexible way using this presented model? Something like for example:

```
    strategy:
      matrix:
        tags: [{tag1: "key1:something", tag2: "key2:something", tag3: "key3:something"}]
```

```
    with:
      tagName: ${{ matrix.tags.tag }}
```

Reusable workflow:

```
on: 
  workflow_call:
    inputs:
      tagName:
        required: true
        type: string
```

```
          tags: |
            - "${{ inputs.tagName }}"
```

**Comment by manchicken** [comment]
@bruno561, I have another question: what is your matrix for here? Are you only using this to make multiple service definitions in the same workflow?

**Reply by bruno561** [reply]
@manchicken Yep! That's the point!
It's a way to create multiple service definitions for services in a single wokflow.

**Reply by manchicken** [reply]
Try something like this and let me know if it works:

```yaml
name: caller_workflow

on:
  workflow_dispatch:

jobs:
  create-service-definition:
    strategy:
      matrix:
        service:
          - service-name-1
          - service-name-2
        team:
          - team1
          - team2
        email:
          - email-1
          - email-2
        slack-channel: 
          - channel1
          - channel2
        docs:
          - |
            - name: doc1
              url: https://doc1.com
              provider: Confluence
          - |
            - name: doc2
              url: https://doc2.com
              provider: Confluence
        links:
          - |
            - name: link1
              url: https://link1.com
              type: dashboard
          - |
            - name: link2
              url: https://link2.com
              type: dashboard
        tags:
          - |
            - tag1: value1
            - tag2: value2
          - |
            - tag1: value3
            - tag2: value4
      fail-fast: false
    uses: arcxp/datadog-service-catalog-metadata-provider@1.1.2
    secrets: inherit
    with:
      service-name: ${{ matrix.service }}
      team: ${{ matrix.team }}
      email: ${{ matrix.email }}
      slack-support-channel: ${{ matrix.slack-channel }}
      docs: ${{ matrix.docs }}
      tags: ${{ matrix.tags }}
```

**Reply by manchicken** [reply]
(I haven't tested this, it's just that this is going to be the approach that will work better since it's in keeping with the shapes of the schema.)

GitHub Actions inputs must always be scalar, so you've gotta make sure your matrix values are always a list of strings.

**Reply by bruno561** [reply]
2 jobs were created, where 1 of them has this value:
```
        tags:
          - |
            - tag1: value1
              tag2: value2
```

And the other one has this:
```
        tags:
          - |
            - tag1: value3
              tag2: value4
```

One overwrites the other.
I remember trying something like this. The pipeline does not "break", but this is not expected behavior.

**Reply by manchicken** [reply]
That is correct. Each of those items in the `tags` list is a string. What did you want to happen?

**Reply by manchicken** [reply]
(Please note, I just updated my prior example to make it correct. Each tag needs to be a YAML-encoded string containing a list of tags.)

```yaml
        tags:
          - |
            - tag1: value1
            - tag2: value2
          - |
            - tag1: value3
            - tag2: value4
```

**Reply by bruno561** [reply]
Sorry, @manchicken 
I had made a mistake in the code. Now the pipeline works. However, in Datadog it did not show the tags. Trying to understand why.
![image](https://github.com/arcxp/datadog-service-catalog-metadata-provider/assets/65369082/06fb2bad-99ae-4c07-9267-15f7bd1c7a00)

![image](https://github.com/arcxp/datadog-service-catalog-metadata-provider/assets/65369082/458282e3-a405-404d-b003-a9c7e0816743)

In my example, I used 1 service with multiple tags.

**Reply by manchicken** [reply]
Can you paste the updated template (with redactions for sensitive information)?

**Reply by bruno561** [reply]
Yep! @manchicken 

```
    strategy:
      matrix:
        service: [something]
        squad: [something]
        email: [something@something.com]
        slack-channel: ["https://something.slack.com/archives/something"]
        docs: ["https://something.com"]
        links: ["https://something.com"]
        tags:
          - |
            - tag1: value1
              tag2: value2
              tag3: value3
      fail-fast: false
    uses: reusable_workflow@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      squadName: ${{ matrix.squad }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-channel }}
      docUrl: ${{ matrix.docs }}
      grafanaUrl: ${{ matrix.links }}
      tagName: ${{ matrix.tags }}
```

Reusable Workflow
```
          tags: |
            - ${{ inputs.tagName }}
```

**Reply by bruno561** [reply]
I also tried with `-` but the workflow breaks:
```
        tags:
          - |
            - tag1: value1
            - tag2: value2
```
Error: Failed to register service with DataDog. Status Code: 400 Body: {"errors":["Bad Request"],"error_details":[{}]}
![image](https://github.com/arcxp/datadog-service-catalog-metadata-provider/assets/65369082/3ead9f1a-9a13-4859-97fc-9a11094f3597)
