### ISSUE TITLE
crash: inputsToRegistryDocument returning non-promise

### ISSUE THREAD

**Issue by hermanbanken** [arcxp/datadog-service-catalog-metadata-provider#108]
**Describe the bug**
Failure in job, due to non-Promise returned from `inputsToRegistryDocument()`.

**To Reproduce**
use yaml below, and version `4d76927255c82b257b15167485e5f1ecaa96b327` (latest)

**Expected behavior**
Working upload

**Screenshots**
<img width="1290" alt="Screenshot 2024-05-06 at 12 59 18" src="https://github.com/arcxp/datadog-service-catalog-metadata-provider/assets/791189/f3db894b-1f04-4b0f-b735-91bdb1322630">

**Workflow definition (PLEASE REDACT ANY SENSITIVE INFORMATION):**

```yaml
on:
  push:

jobs:
  deploy:
    steps:
      - name: Update application in datadog service catalog 
        uses: arcxp/datadog-service-catalog-metadata-provider@4d76927255c82b257b15167485e5f1ecaa96b327 # v2.3.1
        with:
          schema-version: v2.1
          datadog-hostname: api.datadoghq.eu
          datadog-key: ${{ secrets.DD_EU_API_KEY }}
          datadog-app-key: ${{ secrets.DD_EU_APP_KEY }}
          service-name: my-app
          description: my-app is a nice application
          lifecycle: production
          slack-support-channel: https://slack.com/archives/CCCCCCCC
          team: my-team
          email: my-team@my-org.com
          links: |
            - name: ${{ github.repository }}
              url: https://github.com/my-org/my-app
              type: repo
              provider: github
            - name: production api url
              url: https://myapp.com
              type: url    
```

**Additional context**
