### ISSUE TITLE
403 When Trying to Register Service

### ISSUE THREAD

**Issue by ImIOImI** [arcxp/datadog-service-catalog-metadata-provider#80]
**Describe the bug**
Received the error message:
```
Failed to register service with DataDog. Status Code: 403 Body: {"status":"error","code":403,"errors":["Forbidden"],"statuspage":"http://status.us5.datadoghq.com","twitter":"http://twitter.com/datadogops","email":"support@datadoghq.com"}
```

When providing action with valid credentials, confirmed [via curl command as described in the API docs](https://docs.datadoghq.com/api/latest/service-definition/?code-lang=curl#create-or-update-service-definition)

**To Reproduce**
1. Created the GH Action as below
2. Set up secrets
3. manually dispatch the action

**Expected behavior**
I expected the action to trigger, and the service catalog to have been updated

**Screenshots**

**Workflow definition (PLEASE REDACT ANY SENSITIVE INFORMATION):**

```yaml
---
name: Datadog Service Catalog Metadata Provider 

on:
  push:
    branches:
      - main
    paths:
      - 'services/myService/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # This uses the custom action to push the service definition to Datadog.
      - uses: arcxp/datadog-service-catalog-metadata-provider@v2
        with:
          datadog-hostname: api.us5.datadoghq.com
          datadog-key: ${{ secrets.DD_API_KEY }}
          datadog-app-key: ${{ secrets.DD_APP_KEY }}
          github-token: ${{ secrets.GH_TOKEN }}
          service-name: redacted.api
          team: My Team
          email: engineering@mydomain.com
#          slack-support-channel: 'https://team-name-here.slack.com/archives/ABC123'
          tags: |
            - marval:true
          repos: |
            - name: primary service repo
              url: https://github.com/Path/To/Repo
              provider: github
            - name: artifacts repo
              url: https://github.com/Path/To/Artifacts/Repo
              provider: github
```

**Additional context**
